volumes:
  rust-cache:
    name: "rust-cache"
  nanocl-deps:
    name: "nanocl-deps"

networks:
  nanoclbr0:
    name: nanoclbr0
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: nanoclbr0

services:
  nstore:
    container_name: system.nstore.c
    hostname: store.nanocl.internal
    image: docker.io/cockroachdb/cockroach:v25.4.13
    entrypoint: /bin/sh
    tty: true
    networks:
      - nanoclbr0
    ports:
      - 26257:26257
      - 26258:26258
    volumes:
      - ${STATE_DIR:-${HOME}/.nanocl_dev/state}/store:${STATE_DIR:-${HOME}/.nanocl_dev/state}/store
    environment:
      - STATE_DIR=${STATE_DIR:-${HOME}/.nanocl_dev/state}/store
    labels:
      - io.nanocl=enabled
      - io.nanocl.kind=cargo
      - io.nanocl.c=system.nstore
      - io.nanocl.n=system
      - io.nanocl.not-init-c=true
      - io.nanocl.cargo.replica=d5826ac7-1153-4405-a5ff-6737b16aa5f0
      - io.nanocl.cargo.replica-ordinal=0
      - io.nanocl.cargo.container=nstore
      - io.nanocl.cargo.role=app
      - io.nanocl.cargo.essential=true
      - io.nanocl.cargo.network-mode=nanoclbr0
      - io.nanocl.cargo.position=0
    command:
      - -c
      - |
        echo "starting cockroachdb"
        # if [ ! -f "$$STATE_DIR/ca/ca.key" ]; then
        #   echo "generating certs"
        #   mkdir -p $$STATE_DIR/ca $$STATE_DIR/certs $$STATE_DIR/data
        #   cockroach cert create-ca --certs-dir=$$STATE_DIR/certs --ca-key=$$STATE_DIR/ca/ca.key
        #   cockroach cert create-node 127.0.0.1 store.nanocl.internal --certs-dir=$$STATE_DIR/certs --ca-key=$$STATE_DIR/ca/ca.key
        #   cockroach cert create-client root --certs-dir=$$STATE_DIR/certs --ca-key=$$STATE_DIR/ca/ca.key
        # fi
        cockroach start-single-node --listen-addr=:26257 --sql-addr=:26258 --store=$$STATE_DIR/data --insecure

  nmetrics:
    container_name: system.nmetrics.c
    image: ghcr.io/next-hat/metrsd:0.5.8
    tty: true
    environment:
      - LOG_LEVEL=metrsd=info
    networks:
      - nanoclbr0
    command:
      - --hosts
      - unix:///run/nanocl/metrics.sock
    labels:
      - io.nanocl=enabled
      - io.nanocl.kind=cargo
      - io.nanocl.c=system.nmetrics
      - io.nanocl.n=system
      - io.nanocl.not-init-c=true
      - io.nanocl.cargo.replica=08e65023-afcb-40cb-a4be-b8e030a12aa1
      - io.nanocl.cargo.replica-ordinal=0
      - io.nanocl.cargo.container=nmetrics
      - io.nanocl.cargo.role=app
      - io.nanocl.cargo.essential=true
      - io.nanocl.cargo.network-mode=nanoclbr0
      - io.nanocl.cargo.position=0
    volumes:
      - //run/guest-services/nanocl:/run/nanocl

  ncproxy:
    container_name: system.ncproxy.c
    image: ghcr.io/next-hat/nanocl-dev:dev
    tty: true
    profiles:
      - proxy
    network_mode: host
    environment:
      - RUST_BACKTRACE=1
      - STATE_DIR=${STATE_DIR:-${HOME}/.nanocl_dev/state}/proxy
      - NANOCL_NODE=nanocl.internal
    command:
      - watch
      - -w
      - /project/bin/ncproxy/src
      - -x
      - run --no-default-features --features dev --bin ncproxy -- --state-dir ${STATE_DIR:-${HOME}/.nanocl_dev/state}/proxy
    labels:
      - io.nanocl=enabled
      - io.nanocl.kind=cargo
      - io.nanocl.c=system.ncproxy
      - io.nanocl.n=system
      - io.nanocl.not-init-c=true
      - io.nanocl.cargo.replica=8939e8d5-8ca1-4fee-9ff2-d8b20c89df4e
      - io.nanocl.cargo.replica-ordinal=0
      - io.nanocl.cargo.container=ncproxy
      - io.nanocl.cargo.role=app
      - io.nanocl.cargo.essential=true
      - io.nanocl.cargo.network-mode=host
      - io.nanocl.cargo.position=0
    volumes:
      - type: bind
        source: .
        target: /project
      - nanocl-deps:/project/target
      - rust-cache:/usr/local/cargo/registry
      - //run/guest-services/nanocl:/run/nanocl
      - ${STATE_DIR:-${HOME}/.nanocl_dev/state}/proxy:${STATE_DIR:-${HOME}/.nanocl_dev/state}/proxy

  ncdns:
    container_name: system.ncdns.c
    image: ghcr.io/next-hat/nanocl-dev:dev
    tty: true
    profiles:
      - dns
    network_mode: host
    environment:
      - RUST_BACKTRACE=1
      - STATE_DIR=${STATE_DIR:-${HOME}/.nanocl_dev/state}/dns
      - NANOCL_NODE=nanocl.internal
    command:
      - watch
      - -w
      - /project/bin/ncdns/src
      - -x
      - run --no-default-features --features dev --bin ncdns -- --state-dir ${STATE_DIR:-${HOME}/.nanocl_dev/state}/dns
    labels:
      - io.nanocl=enabled
      - io.nanocl.kind=cargo
      - io.nanocl.c=system.ncdns
      - io.nanocl.n=system
      - io.nanocl.not-init-c=true
      - io.nanocl.cargo.replica=9318217b-d461-4f5f-a0bb-d73446fdb93b
      - io.nanocl.cargo.replica-ordinal=0
      - io.nanocl.cargo.container=ncdns
      - io.nanocl.cargo.role=app
      - io.nanocl.cargo.essential=true
      - io.nanocl.cargo.network-mode=host
      - io.nanocl.cargo.position=0
    volumes:
      - type: bind
        source: .
        target: /project
      - nanocl-deps:/project/target
      - rust-cache:/usr/local/cargo/registry
      - //run/guest-services/nanocl:/run/nanocl
      - ${STATE_DIR:-${HOME}/.nanocl_dev/state}/dns:${STATE_DIR:-${HOME}/.nanocl_dev/state}/dns

  nanocld:
    container_name: system.ndaemon.c
    image: ghcr.io/next-hat/nanocl-dev:dev
    tty: true
    hostname: nanocl.internal
    # network_mode: host
    ports:
      - 8585:8585
      - 9443:9443
    networks:
      - nanoclbr0
    labels:
      - io.nanocl=enabled
      - io.nanocl.kind=cargo
      - io.nanocl.c=system.ndaemon
      - io.nanocl.n=system
      - io.nanocl.not-init-c=true
      - io.nanocl.cargo.replica=270a8143-4f58-4504-9c30-05924e2cc7d4
      - io.nanocl.cargo.replica-ordinal=0
      - io.nanocl.cargo.container=ndaemon
      - io.nanocl.cargo.role=app
      - io.nanocl.cargo.essential=true
      - io.nanocl.cargo.network-mode=nanoclbr0
      - io.nanocl.cargo.position=0
    environment:
      - RUST_BACKTRACE=1
    volumes:
      - type: bind
        source: .
        target: /project
      - nanocl-deps:/project/target
      - rust-cache:/usr/local/cargo/registry
      - /var/run/docker.sock:/run/docker.sock
      - //run/guest-services/nanocl:/run/nanocl
      - ${STATE_DIR:-${HOME}/.nanocl_dev/state}:${STATE_DIR:-${HOME}/.nanocl_dev/state}
    command:
      - watch
      - -w
      - /project/bin/nanocld/src
      - -x
      - |
        run --no-default-features \
          --features dev \
          --bin nanocld \
          -- \
          --hosts unix:///run/nanocl/nanocl.sock \
          --gid 1001 \
          --store-addr postgresql://root:root@store.nanocl.internal:26258/defaultdb?options=-c%20autocommit_before_ddl%3Doff \
          --hosts tcp://0.0.0.0:9443 \
          --cert ./tests/server.crt \
          --cert-key ./tests/server.key \
          --cert-ca ./tests/ca.crt \
          --state-dir ${STATE_DIR:-${HOME}/.nanocl_dev/state}

  dbeaver:
    container_name: system.dbeaver.c
    image: dbeaver/cloudbeaver:25.0
    tty: true
    user: root
    hostname: dbeaver.nanocl.internal
    networks:
      - nanoclbr0
    profiles:
      - debug
    ports:
      - 9090:8978
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    labels:
      - io.nanocl=enabled
      - io.nanocl.kind=cargo
      - io.nanocl.c=system.dbeaver
      - io.nanocl.n=system
      - io.nanocl.not-init-c=true
      - io.nanocl.cargo.replica=bf3484e4-d743-4068-89af-2c18423c83dd
      - io.nanocl.cargo.replica-ordinal=0
      - io.nanocl.cargo.container=dbeaver
      - io.nanocl.cargo.role=app
      - io.nanocl.cargo.essential=true
      - io.nanocl.cargo.network-mode=nanoclbr0
      - io.nanocl.cargo.position=0
    volumes:
      - ${STATE_DIR:-${HOME}/.nanocl_dev}/dbeaver:/opt/cloudbeaver/workspace

  ncvpnkit:
    container_name: system.ncvpnkit.c
    image: ghcr.io/next-hat/nanocl-dev:dev
    tty: true
    networks:
      - nanoclbr0
    hostname: ncvpnkit.nanocl.internal
    profiles:
      - vpnkit
    environment:
      - USER_HOME=${HOME}
      - RUST_BACKTRACE=1
    labels:
      - io.nanocl=enabled
      - io.nanocl.kind=cargo
      - io.nanocl.c=system.ncvpnkit
      - io.nanocl.n=system
      - io.nanocl.not-init-c=true
      - io.nanocl.cargo.replica=fd920f8e-0cd5-43a2-a4b5-be4c363a9f70
      - io.nanocl.cargo.replica-ordinal=0
      - io.nanocl.cargo.container=ncvpnkit
      - io.nanocl.cargo.role=app
      - io.nanocl.cargo.essential=true
      - io.nanocl.cargo.network-mode=nanoclbr0
      - io.nanocl.cargo.position=0
    volumes:
      - type: bind
        source: .
        target: /project
      - nanocl-deps:/project/target
      - rust-cache:/usr/local/cargo/registry
      - //run/guest-services/nanocl:/run/nanocl
      - //run/host-services/backend.sock:/run/host-services/backend.sock
    command:
      - watch
      - -w
      - /project/bin/ncvpnkit/src
      - -x
      - run --no-default-features --features dev --bin ncvpnkit
