[config]
default_to_workspace = false

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]

# Clean dependencies and build cache
[tasks.clean]
command = "cargo"
args = ["clean"]

# Run daemon
[tasks.run-daemon]
command = "cargo"
args = ["run", "--bin", "nanocld", "${@}"]

# Run cli
[tasks.run-cli]
command = "cargo"
args = [
  "run",
  "--no-default-features",
  "--features",
  "dev",
  "--bin",
  "nanocl",
  "${@}",
]

# Test daemon
[tasks.tests-daemon]
command = "cargo"
args = [
  "test",
  "--no-default-features",
  "--features",
  "test",
  "${@}",
  "--bin",
  "nanocld",
  "--",
  "--test-threads",
  "1",
]

# Test nanocld_client
[tasks.tests-client]
command = "cargo"
args = ["nextest", "run", "-p", "nanocld_client"]

# Test Cli
[tasks.tests-cli]
command = "cargo"
args = [
  "test",
  "--no-default-features",
  "--features",
  "test",
  "${@}",
  "--bin",
  "nanocl",
  "--",
  "--test-threads",
  "1",
]

# Test ncproxy
[tasks.tests-ncproxy]
command = "cargo"
args = [
  "test",
  "--no-default-features",
  "--features",
  "test",
  "${@}",
  "--bin",
  "ncproxy",
  "--",
  "--test-threads",
  "1",
]

# Test all
[tasks.tests]
command = "cargo"
args = [
  "test",
  "--no-default-features",
  "--features",
  "test",
  "${@}",
  "--",
  "--test-threads",
  "1",
]

# Test all with debug output
[tasks.tests-debug]
command = "cargo"
args = ["test", "--no-default-features", "--features", "test", "--nocapture"]

[tasks.dev]
command = "docker"
args = ["compose", "up"]

# Test coverage
[tasks.cov]
command = "cargo"
args = ["llvm-cov", "--no-default-features", "--features", "test", "-j", "1"]

# Test all with coverage for codecov
[tasks.covgen]
command = "cargo"
args = [
  "llvm-cov",
  "--no-default-features",
  "--features",
  "test",
  "--output-path",
  "./lcov.info",
  "--lcov",
  "--",
  "--test-threads",
  "1",
]

# Release
[tasks.release]
command = "cargo"
args = ["build", "--release"]
