# BIND_HTTP: {{ listen }}
{% if ssl %}# BIND_HTTPS: {{ listen_https }}
{% endif %}{% if limit_req_zone %}# Rate limiting stick-table for {{ key }}
backend st_{{ key }}
  stick-table type ip size {{ limit_req_zone.Size }}m expire 10s store http_req_rate(10s)
{% endif %}

# Routing rules for {{ key }}
{% if domain %}acl host_{{ key }} hdr(host),field(1,:) -i {{ domain }}
{% if hsts %}http-response set-header Strict-Transport-Security "max-age={{ hsts.MaxAge }}{% if hsts.IncludeSubDomains %}; includeSubDomains{% endif %}{% if hsts.Preload %}; preload{% endif %}" if { ssl_fc } host_{{ key }}
{% endif %}{% endif %}

{% for location in locations %}# Location {{ location.path }}
acl {{ key }}_loc{{ forloop.index }} path_beg {{ location.path }}

{% if location.allowed_ips %}# IP allowlist for {{ location.path }}
{% for allowed_ip in location.allowed_ips %}acl {{ key }}_loc{{ forloop.index }}_allowed_ip src {{ allowed_ip }}
{% endfor %}http-request deny if {{ key }}_loc{{ forloop.index }} !{% for allowed_ip in location.allowed_ips %}{{ key }}_loc{{ forloop.index }}_allowed_ip{% if forloop.last == false %} !{% endif %}{% endfor %}
{% endif %}

{% if location.limit_req %}# Rate limiting for {{ location.path }}
http-request track-sc0 src table st_{{ key }} if {{ key }}_loc{{ forloop.index }}
http-request deny deny_status 429 if {{ key }}_loc{{ forloop.index }} { sc_http_req_rate(0) gt {{ location.limit_req.Burst }} }
{% endif %}

{% if location.redirect %}# Redirect for {{ location.path }}
http-request redirect code {{ location.redirect }} location {{ location.upstream_key }} if {% if domain %}host_{{ key }} {% endif %}{{ key }}_loc{{ forloop.index }}
{% else %}
{% if location.headers %}# Custom headers for {{ location.path }}
{% for header in location.headers %}http-request set-header {{ header }} if {% if domain %}host_{{ key }} {% endif %}{{ key }}_loc{{ forloop.index }}
{% endfor %}{% endif %}

use_backend bk_{{ location.upstream_key | split: "//" | last }} if {% if domain %}host_{{ key }} {% endif %}{{ key }}_loc{{ forloop.index }}
{% endif %}
{% endfor %}

{% if locations.size > 0 %}# Default backend for {{ key }}
{% if domain %}use_backend bk_{{ locations[0].upstream_key | split: "//" | last }} if host_{{ key }}
{% endif %}{% endif %}


