frontend ft_{{ key }}
  bind {{ listen }}{% if protocol == "udp" %} proto udp{% endif %}{% if ssl %} ssl crt {{ ssl.Certificate }}{% endif %}
  mode tcp
  log-format '{"remote_addr":"%ci","time_local":"%t","frontend":"%f","backend":"%b","server":"%s","tw":%Tw,"tc":%Tc,"tt":%Tt,"bytes_read":%B,"bytes_sent":%U,"upstream_addr":"%si:%sp"}'
  log global
  default_backend bk_{{ upstream_key }}
