backend bk_{{ key }}
  mode {{ mode }}
  balance roundrobin
  {% for addr in addresses %}server {{ key }}_{{ forloop.index }} {{ addr }}:{{ port }}{% if ssl %} ssl crt {{ ssl.Certificate }}{% if ssl.VerifyClient %} verify required ca-file {{ ssl.CertificateClient }}{% else %} verify none{% endif %}{% if version %}{% if version == 2 %} alpn h2{% elsif version == 1.1 %} alpn http/1.1{% endif %}{% endif %}{% endif %}
  {% endfor %}

