backend bk_{{ key }}
  mode {{ mode }}
  balance roundrobin
  {% for addr in addresses %}server {{ key }}_{{ forloop.index }} {{ addr }}:{{ port }}{% if ssl %} ssl crt {{ ssl.Certificate }}{% if ssl.VerifyClient %} verify required ca-file {{ ssl.CertificateClient }}{% else %} verify none{% endif %}{% endif %} check
  {% endfor %}
