[package]
name = "prismar_derive"
version = "0.1.0"
edition = "2024"
authors = ["nanocl contributors <team@next-hat.com>"]
description = "Derive macros for prismar"
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full", "extra-traits"] }
