ApiVersion = "v0.13"

Namespace = "global"

[[Cargoes]]
Name = "deploy-example"

[[Cargoes.Containers]]
Name = "deploy-example"
Image = "ghcr.io/next-hat/nanocl-get-started:latest"
Env = ["APP=GET_STARTED1"]

[[Cargoes]]
Name = "deploy-example2"

[[Cargoes.Containers]]
Name = "deploy-example2"
Image = "ghcr.io/next-hat/nanocl-get-started:latest"
Env = ["APP=GET_STARTED2"]


[[Resources]]
Name = "deploy-example.com"
Kind = "ncproxy.io/rule"

[[Resources.Data.Rules]]
Domain = "deploy-example.com"
Network = "All"

[[Resources.Data.Rules.Locations]]
Path = "/"

[Resources.Data.Rules.Locations.Target]
Key = "global.deploy-example2.c"
Port = 9_000

[[Resources.Data.Rules.Locations]]
Path = "/v1"

[Resources.Data.Rules.Locations.Target]
Key = "global.deploy-example.c"
Port = 9_000

[[Resources.Data.Rules.Locations]]
Path = "/v2"

[Resources.Data.Rules.Locations.Target]
Key = "global.deploy-example2.c"
Port = 9_000
